-- Enterprise finance Oracle schema blueprint.
-- Generate production migrations from EF after choosing the Oracle provider and naming convention.

CREATE TABLE FINANCE_TENANTS (
  ID VARCHAR2(64) PRIMARY KEY,
  NAME NVARCHAR2(200) NOT NULL,
  CODE VARCHAR2(40) NOT NULL UNIQUE,
  BASE_CURRENCY NUMBER(3) NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_BY VARCHAR2(128),
  CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  MODIFIED_BY VARCHAR2(128),
  MODIFIED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE FINANCE_BRANCHES (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  NAME NVARCHAR2(200) NOT NULL,
  CODE VARCHAR2(40) NOT NULL,
  TYPE NUMBER(3) NOT NULL,
  CITY NVARCHAR2(100),
  MANAGER_USER_ID VARCHAR2(64),
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT UX_FIN_BRANCH_TENANT_CODE UNIQUE (TENANT_ID, CODE),
  CONSTRAINT FK_FIN_BRANCH_TENANT FOREIGN KEY (TENANT_ID) REFERENCES FINANCE_TENANTS(ID)
);

CREATE TABLE COST_CENTERS (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  BRANCH_ID VARCHAR2(64),
  CODE VARCHAR2(60) NOT NULL,
  NAME NVARCHAR2(200) NOT NULL,
  PARENT_COST_CENTER_ID VARCHAR2(64),
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT UX_COST_CENTER_TENANT_CODE UNIQUE (TENANT_ID, CODE),
  CONSTRAINT FK_COST_CENTER_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES FINANCE_BRANCHES(ID),
  CONSTRAINT FK_COST_CENTER_PARENT FOREIGN KEY (PARENT_COST_CENTER_ID) REFERENCES COST_CENTERS(ID)
);

CREATE TABLE CHART_OF_ACCOUNTS (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  CODE VARCHAR2(80) NOT NULL,
  NAME NVARCHAR2(250) NOT NULL,
  TYPE NUMBER(3) NOT NULL,
  NORMAL_BALANCE NUMBER(3) NOT NULL,
  PARENT_ACCOUNT_ID VARCHAR2(64),
  IS_POSTING_ALLOWED NUMBER(1) DEFAULT 1 NOT NULL,
  IS_SYSTEM_ACCOUNT NUMBER(1) DEFAULT 0 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT UX_COA_TENANT_CODE UNIQUE (TENANT_ID, CODE),
  CONSTRAINT FK_COA_PARENT FOREIGN KEY (PARENT_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNTS(ID)
);

CREATE TABLE FINANCE_ACCOUNTS (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  BRANCH_ID VARCHAR2(64),
  LEDGER_ACCOUNT_ID VARCHAR2(64) NOT NULL,
  NAME NVARCHAR2(200) NOT NULL,
  TYPE NUMBER(3) NOT NULL,
  CURRENCY NUMBER(3) NOT NULL,
  CURRENT_BALANCE NUMBER(18,2) DEFAULT 0 NOT NULL,
  BANK_NAME NVARCHAR2(120),
  ACCOUNT_NUMBER_MASKED VARCHAR2(80),
  REQUIRES_RECONCILIATION NUMBER(1) DEFAULT 1 NOT NULL,
  IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
  CONSTRAINT FK_FIN_ACCOUNT_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES FINANCE_BRANCHES(ID),
  CONSTRAINT FK_FIN_ACCOUNT_LEDGER FOREIGN KEY (LEDGER_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNTS(ID)
);

CREATE TABLE ACCOUNTING_PERIODS (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  NAME NVARCHAR2(120) NOT NULL,
  STARTS_ON TIMESTAMP NOT NULL,
  ENDS_ON TIMESTAMP NOT NULL,
  IS_CLOSED NUMBER(1) DEFAULT 0 NOT NULL,
  CLOSED_ON TIMESTAMP,
  CLOSED_BY VARCHAR2(128),
  CONSTRAINT UX_PERIOD_RANGE UNIQUE (TENANT_ID, STARTS_ON, ENDS_ON)
);

CREATE TABLE JOURNAL_ENTRIES (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  JOURNAL_NUMBER VARCHAR2(80) NOT NULL,
  ACCOUNTING_DATE TIMESTAMP NOT NULL,
  STATUS NUMBER(3) NOT NULL,
  SOURCE_DOCUMENT_TYPE NUMBER(3) NOT NULL,
  SOURCE_DOCUMENT_ID VARCHAR2(128),
  BRANCH_ID VARCHAR2(64),
  DESCRIPTION NVARCHAR2(1000),
  POSTED_ON TIMESTAMP,
  POSTED_BY VARCHAR2(128),
  REVERSAL_OF_JOURNAL_ENTRY_ID VARCHAR2(64),
  CONSTRAINT UX_JE_TENANT_NUMBER UNIQUE (TENANT_ID, JOURNAL_NUMBER),
  CONSTRAINT FK_JE_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES FINANCE_BRANCHES(ID),
  CONSTRAINT FK_JE_REVERSAL FOREIGN KEY (REVERSAL_OF_JOURNAL_ENTRY_ID) REFERENCES JOURNAL_ENTRIES(ID)
);

CREATE TABLE JOURNAL_ENTRY_LINES (
  ID VARCHAR2(64) PRIMARY KEY,
  JOURNAL_ENTRY_ID VARCHAR2(64) NOT NULL,
  LEDGER_ACCOUNT_ID VARCHAR2(64) NOT NULL,
  COST_CENTER_ID VARCHAR2(64),
  BRANCH_ID VARCHAR2(64),
  DEBIT_AMOUNT NUMBER(18,2) DEFAULT 0 NOT NULL,
  CREDIT_AMOUNT NUMBER(18,2) DEFAULT 0 NOT NULL,
  CURRENCY NUMBER(3) NOT NULL,
  EXCHANGE_RATE_TO_BASE NUMBER(18,8) DEFAULT 1 NOT NULL,
  DESCRIPTION NVARCHAR2(1000),
  CONSTRAINT FK_JEL_ENTRY FOREIGN KEY (JOURNAL_ENTRY_ID) REFERENCES JOURNAL_ENTRIES(ID),
  CONSTRAINT FK_JEL_ACCOUNT FOREIGN KEY (LEDGER_ACCOUNT_ID) REFERENCES CHART_OF_ACCOUNTS(ID),
  CONSTRAINT FK_JEL_COST_CENTER FOREIGN KEY (COST_CENTER_ID) REFERENCES COST_CENTERS(ID),
  CONSTRAINT FK_JEL_BRANCH FOREIGN KEY (BRANCH_ID) REFERENCES FINANCE_BRANCHES(ID),
  CONSTRAINT CK_JEL_ONE_SIDE CHECK ((DEBIT_AMOUNT > 0 AND CREDIT_AMOUNT = 0) OR (CREDIT_AMOUNT > 0 AND DEBIT_AMOUNT = 0))
);

CREATE TABLE FINANCIAL_TRANSACTIONS (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  CODE VARCHAR2(80) NOT NULL,
  STATUS NUMBER(3) NOT NULL,
  SOURCE_DOCUMENT_TYPE NUMBER(3) NOT NULL,
  SOURCE_DOCUMENT_ID VARCHAR2(128),
  DIRECTION NUMBER(3) NOT NULL,
  AMOUNT NUMBER(18,2) NOT NULL,
  CURRENCY NUMBER(3) NOT NULL,
  PAYMENT_METHOD NUMBER(3) NOT NULL,
  FINANCE_ACCOUNT_ID VARCHAR2(64) NOT NULL,
  BRANCH_ID VARCHAR2(64),
  COST_CENTER_ID VARCHAR2(64),
  JOURNAL_ENTRY_ID VARCHAR2(64),
  CATEGORY NVARCHAR2(120),
  COUNTERPARTY_ID VARCHAR2(128),
  COUNTERPARTY_NAME NVARCHAR2(250),
  DESCRIPTION NVARCHAR2(1000),
  TRANSACTION_DATE TIMESTAMP NOT NULL,
  APPROVED_BY VARCHAR2(128),
  APPROVED_ON TIMESTAMP,
  IS_AUTOMATED NUMBER(1) DEFAULT 0 NOT NULL,
  CONSTRAINT UX_FIN_TX_TENANT_CODE UNIQUE (TENANT_ID, CODE),
  CONSTRAINT FK_FIN_TX_ACCOUNT FOREIGN KEY (FINANCE_ACCOUNT_ID) REFERENCES FINANCE_ACCOUNTS(ID),
  CONSTRAINT FK_FIN_TX_JOURNAL FOREIGN KEY (JOURNAL_ENTRY_ID) REFERENCES JOURNAL_ENTRIES(ID)
);

CREATE TABLE FINANCIAL_AUDIT_LOGS (
  ID VARCHAR2(64) PRIMARY KEY,
  TENANT_ID VARCHAR2(64) NOT NULL,
  ENTITY_NAME VARCHAR2(120) NOT NULL,
  ENTITY_ID VARCHAR2(80) NOT NULL,
  ACTION VARCHAR2(80) NOT NULL,
  BEFORE_JSON CLOB,
  AFTER_JSON CLOB,
  CORRELATION_ID VARCHAR2(120),
  IP_ADDRESS VARCHAR2(80),
  CREATED_BY VARCHAR2(128),
  CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX IX_JE_TENANT_DATE ON JOURNAL_ENTRIES(TENANT_ID, ACCOUNTING_DATE);
CREATE INDEX IX_JEL_ACCOUNT ON JOURNAL_ENTRY_LINES(LEDGER_ACCOUNT_ID, JOURNAL_ENTRY_ID);
CREATE INDEX IX_JEL_BRANCH_COST ON JOURNAL_ENTRY_LINES(BRANCH_ID, COST_CENTER_ID);
CREATE INDEX IX_FIN_TX_TENANT_DATE ON FINANCIAL_TRANSACTIONS(TENANT_ID, TRANSACTION_DATE);
CREATE INDEX IX_AUDIT_ENTITY ON FINANCIAL_AUDIT_LOGS(TENANT_ID, ENTITY_NAME, ENTITY_ID, CREATED_TIME);
